spring.application.name=hexaquiz

api.security.token.secret=${SPRING_JWT_SECRET}
jwt.access-token.expiration=
jwt.refresh-token.expiration=

spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

